Feature: The operator IDE (routed multi-instance designer)
  The designer (instance 4) is a URL-routed multi-instance IDE, authored as an explicit custom
  `fn render()` over a `Db { designs: set of Design }` meta-schema. A `Design` is a WHOLE app —
  structured `types` plus the other app-document sections (initialData/common/ui) as source text. An
  instance references its design by the registry `app` LABEL (an instance's `app` == its design's
  `label`), and the IDE matches `sys.instances` rows to `db.designs` by it. `/instances` lists the
  hosted instances with their matched designs; `/instances/<id>` edits the design that instance
  references (a type/prop editor + code-area inputs for ui/common/initialData) and publishes it back.
  The seeded designs are FAITHFUL copies of the committed apps the kernel runs (instance = the todo
  app, crm, shop — generated by DesignerSeedGenerator), so editing one shows that app's REAL types and
  UI and publishing re-publishes the REAL app. Driven against a REAL kernel host (the designer needs a
  non-empty `sys.instances`), through a browser. Milestone 10.

  @milestone-10 @single-user
  Scenario: The instances route lists the hosted instances with their designs
    Given the operator IDE is running on a kernel hosting instances "instance" and "crm"
    When I open the instances list
    Then the list shows the instance "instance" with design "instance"
    And the list shows the instance "crm" with design "crm"

  # The "instance" design is the REAL todo app: its types include TodoItem and its UI is the real
  # custom `fn render()` — so the editor shows that app's actual content, not a placeholder.
  @milestone-10 @single-user
  Scenario: Editing an instance shows the design it references — its real types and its UI text
    Given the operator IDE is running on a kernel hosting instances "instance" and "crm"
    When I open the instances list
    And I edit the instance "instance"
    Then the design editor shows a type named "TodoItem"
    And the design editor shows the design's UI text in a textarea

  # Renaming a referenced type is the honest workflow: the type AND the prop that references it both
  # change, so the projected app stays valid. Renaming TodoItem (referenced only by TodoList.items)
  # to Widget and retyping that prop publishes a valid app document carrying the new name.
  @milestone-10 @single-user
  Scenario: Renaming a type and publishing updates the target instance's app document
    Given the operator IDE is running on a kernel hosting instances "instance" and "crm"
    When I open the instances list
    And I edit the instance "instance"
    And I rename the type "TodoItem" to "Widget"
    And I retype the prop "items" to "Widget"
    And I publish the design
    Then the "instance" instance's app document describes the type "Widget"

  # The code-area editors are multi-line <textarea>s with working two-way binding: editing the
  # UI textarea (a multi-line render) updates the bound design, and publishing projects the
  # edited UI into the target instance's app document.
  @milestone-10 @single-user
  Scenario: Editing the UI textarea and publishing updates the target instance's app document
    Given the operator IDE is running on a kernel hosting instances "instance" and "crm"
    When I open the instances list
    And I edit the instance "instance"
    And I replace the design's UI with a render returning "edited-by-textarea"
    And I publish the design
    Then the "instance" instance's app document renders "edited-by-textarea"
